apiVersion: v1
kind: Service
metadata:
  name: anomaly-agent-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: anomaly-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
