apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anomaly-response-agent
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/AmericanExpress/agentic_ai.git'
    targetRevision: main
    path: autonomous_anomaly_resposne_agent/infra/helm_charts/anomaly-agent
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: anomaly-agents-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
